import base from '@munaxa/config-eslint/next.js';

/**
 * The web app owns screens, not components.
 *
 * Every button, card, table and dialog comes from `@munaxa/ui`; a second one written here is
 * the duplication the whole platform exists to prevent
 * ([rulebook §6–7](https://github.com/munaxa/munaxa-platform)). Re-exporting the platform
 * through a local barrel is equally forbidden — it hides which components a product actually
 * uses, and makes an upgrade impossible to review.
 */
export default [
  {
    // Generated by `next build`, and regenerated on every build: linting it means linting
    // Next.js's output, and it is not committed.
    ignores: ['.next/**', 'next-env.d.ts'],
  },
  ...base,
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@munaxa/platform', '@munaxa/platform/*'],
              message: 'Import from @munaxa/ui, not from the implementation package behind it.',
            },
            {
              group: ['*/features/*/components/*', '*/features/*/hooks/*'],
              message:
                "A feature may not reach into another feature's internals. Import its public surface, or move the shared piece to features/shared on the third consumer.",
            },
          ],
        },
      ],
    },
  },
];
