-- One live blob per digest, and per key — release-candidate validation, D-12.
--
-- ## What was broken
--
-- `uq_file_object_checksum` and `uq_file_object_key` were full indexes: one row per digest per
-- tenant for ever. Every reader of `file_object` asks for live rows only — `findByChecksum`,
-- `findById`, `adjustRefCount`, `listUnreferenced`, the integrity sweep, the reaper, the dashboard
-- and the storage report all carry `deleted_at IS NULL` — and the reaper is the one writer that
-- retires a row, in the transaction that removes its object from the store.
--
-- So once a blob had been reclaimed, uploading the same bytes again in that tenant could never
-- succeed. `completeUploadSession` looked for a live row, found none, copied the staged bytes to the
-- content key and inserted; the insert met the retired row in the full index and was skipped
-- (`ON CONFLICT DO NOTHING`); the re-read for the winner found no live row either, and the upload
-- answered 503 "Object storage is unavailable" — leaving the bytes it had just copied at the
-- content key with no row to name them. Every later attempt did the same. A derived artefact
-- (a rendition, an export) regenerated byte-for-byte after its first copy was reclaimed met the
-- same refusal through `storeDerived`.
--
-- ## What this says instead
--
-- The invariant the full indexes were written for is kept exactly: at most one *live* row per
-- digest and per key in a tenant, so one object has one reference count and deduplication still
-- converges on it. A retired row is history — its object is gone, its count is frozen at zero
-- because `adjustRefCount` refuses a deleted row, nothing reads it as content, and its
-- `deleted_at` / `deleted_by` are the only record of when the bytes were reclaimed — so it no
-- longer holds the digest's slot. It is not revived and nothing about it is rewritten.
--
-- ## Existing data
--
-- Nothing is rewritten. Every existing row satisfied the full indexes, so it satisfies the
-- partial ones. The swap runs inside the migration's transaction, so there is no moment without
-- a uniqueness guarantee on live rows.

DROP INDEX "uq_file_object_checksum";
CREATE UNIQUE INDEX "uq_file_object_checksum" ON "file_object"("tenant_id", "checksum_sha256")
  WHERE "deleted_at" IS NULL;

DROP INDEX "uq_file_object_key";
CREATE UNIQUE INDEX "uq_file_object_key" ON "file_object"("tenant_id", "storage_key")
  WHERE "deleted_at" IS NULL;
